version: "3.7"

services:
  account:
    image: account:latest
    depends_on:
      - account_db
    environment:
      DATABASE_URL: postgres://vivian:123456@account_db/vivian?sslmode=disable
    restart: on-failure

  catalog:
    image: catalog:latest
    depends_on:
      - catalog_db
    environment:
      DATABASE_URL: http://catalog_db:9200
    restart: on-failure

  order:
    image: order:latest
    depends_on:
      - order_db
    environment:
      DATABASE_URL: postgres://vivian:123456@order_db/vivian?sslmode=disable
      ACCOUNT_SERVICE_URL: account:8080
      CATALOG_SERVICE_URL: catalog:8080
    restart: on-failure

  graphql:
    build:
      context: .
      dockerfile: ./graphql/app.dockerfile
    ports:
      - 8000:8080
    depends_on:
      - account
      - catalog
    environment:
      ACCOUNT_SERVICE_URL: account:8080
      CATALOG_SERVICE_URL: catalog:8080
      ORDER_SERVICE_URL: order:8080
    restart: on-failure

  account_db:
    build:
      context: ./account
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: vivian
      POSTGRES_USER: vivian
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped

  catalog_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g


  order_db:
    build:
      context: ./order
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: vivian
      POSTGRES_USER: vivian
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped